# Generated by Django 5.1.3 on 2024-11-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_library_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
