# Generated by Django 5.1.3 on 2024-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_delete_popular_library_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
